# Form implementation generated from reading ui file '../pyqtgraph/examples/exampleLoaderTemplate.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from pyqtgraph.Qt import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(846, 552)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loadBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout.addWidget(self.loadBtn, 6, 0, 2, 2)
        # self.exampleTree = QtWidgets.QTreeWidget(self.layoutWidget)
        # self.exampleTree.setObjectName("exampleTree")
        # self.exampleTree.headerItem().setText(0, "1")
        # self.exampleTree.header().setVisible(False)

        self.qubitsList = QtWidgets.QListWidget()

        self.gridLayout.addWidget(self.qubitsList, 3, 0, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        font = QtGui.QFont()
        font.setBold(True)

        # self.readoutViewer = pg.PlotWidget()
        # self.readoutViewer = pg.GraphicsLayoutWidget()
        # self.readoutViewer = QtWidgets.QWidget()
        self.readoutViewer = pg.LayoutWidget()

        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.readoutViewer.setFont(font)
        self.readoutViewer.setObjectName("readoutViewer")
        self.verticalLayout.addWidget(self.readoutViewer)
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyQtGraph"))
        self.loadBtn.setText(_translate("Form", "Show data"))
