# On Linux, place this file in your home directory ~/, and remove the ".example"
# On Windows, place it in your C:/Users/username directory, and remove the ".example"
[qmm]
host = "172.16.33.101"
cluster_name = "Cluster_83"
