name: released
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.13
      - uses: Gr1N/setup-poetry@v8
      - name: Build package
        run: |
          export RELEASE_VERSION="${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          poetry version ${RELEASE_VERSION}
          poetry build
      - name: Update pypi
        run: |
          pip install twine
          twine upload -u ${{secrets.PIPY_TOKEN_USER}} -p ${{secrets.PIPY_TOKEN_PWD}} dist/*
      - name: Upload assets
        uses: qm-devops/qm-upload-release-assets@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: |
            ./dist/*.tar.gz
            ./dist/*.whl